"use client"

import type React from "react"
import { createContext, useContext, useState } from "react"

type Language = "en" | "vi"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    // Header
    notifications: "Notifications",
    profile: "Profile",
    logout: "Logout",

    // Menu
    dashboard: "Dashboard",
    warehouse_operations: "Warehouse Operations",
    stock_onhand: "Stock Onhand",
    goods_receipt: "Goods Receipt",
    goods_issue: "Goods Issue",
    inventory_count: "Inventory Count",
    goods_transfer: "Goods Transfer",
    putaway: "Putaway",
    master_data: "Master Data",
    uom: "UoM",
    partner: "Partner",
    organization: "Organization",
    branch: "Branch",
    warehouse: "Warehouse",
    location: "Location",
    goods_management: "Goods Management",
    goods_type: "Goods Type",
    model_goods: "Model Goods",
    reports: "Reports",
    authentication: "Authentication",

    // Table
    search: "Search",
    filter: "Filter",
    export_excel: "Export to Excel",
    import_excel: "Import from Excel",
    column_visibility: "Column Visibility",
    showing: "Showing",
    of: "of",
    entries: "entries",
    page: "Page",

    // Actions
    add_new: "Add New",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    save_close: "Save & Close",
    cancel: "Cancel",
    confirm: "Confirm",
    back: "Back",
    view_details: "View Details",

    // Footer
    copyright: "© 2025 Delfi Tri Nguyen. All rights reserved.",
    version: "Version: 1.0.1",

    // Common
    created_by: "Created By",
    created_at: "Created At",
    updated_by: "Updated By",
    updated_at: "Updated At",
    status: "Status",
    actions: "Actions",
    code: "Code",
    name: "Name",
    description: "Description",

    // UoM Module
    uom_code: "UoM Code",
    uom_name: "UoM Name",
    measurement_type: "Measurement Type",
    uom_type: "UoM Type",
    base_uom: "Base UoM",
    conversion_factor: "Conversion Factor",
    active: "Active",
    inactive: "Inactive",
    base: "Base",
    alt: "Alt",
    piece: "Piece",
    weight: "Weight",
    volume: "Volume",
    length: "Length",
    area: "Area",
    time: "Time",
    no_uom_message: "No UoM defined yet. Create your first one.",
    no_results_message: "No results found.",
    uom_details: "UoM Details",
    create_uom: "Create UoM",
    edit_uom: "Edit UoM",
    delete_uom: "Delete UoM",
    confirm_delete: "Confirm Delete",
    type_code_to_confirm: "Type the UoM Code to confirm deletion",
    cannot_delete_referenced: "Cannot delete UoM because it is already referenced.",
    select_base_uom: "Please select a Base UoM (Each group must have exactly 1 Base).",
    conversion_factor_greater_zero: "Conversion Factor must be greater than 0.",
    cannot_have_multiple_bases: "Cannot assign more than 1 Base per group.",
    inactive_confirmation: "Inactive UoM cannot be used in new transactions but remains in history.",
    audit_information: "Audit Information",
    manage_uom: "Manage unit of measurement definitions",
    uom_required: "UoM Code is required",
    name_required: "UoM Name is required",
    measurement_type_required: "Measurement Type is required",
    uom_type_required: "UoM Type is required",
    code_must_be_unique: "UoM Code must be unique",
    required: "Required",
    view: "View",
    delete_confirmation_message: "Are you sure you want to delete this UoM? This action cannot be undone.",

    // Partner Module
    partner_code: "Partner Code",
    partner_name: "Partner Name",
    partner_type: "Partner Type",
    tax_code: "Tax Code",
    phone: "Phone",
    email: "Email",
    address: "Address",
    contact_person: "Contact Person",
    customer: "Customer",
    supplier: "Supplier",
    carrier: "Carrier",
    other: "Other",
    no_partner_message: "No partner found. Create your first partner.",
    no_matching_partner: "No matching partner found.",
    partner_details: "Partner Details",
    create_partner: "Create Partner",
    edit_partner: "Edit Partner",
    delete_partner: "Delete Partner",
    manage_partner: "Manage partner information",
    partner_code_exists: "Partner Code already exists. Please choose another.",
    partner_code_required: "Partner Code is required",
    partner_name_required: "Partner Name is required",
    invalid_email: "Invalid email format",
    invalid_phone: "Invalid phone format",
    cannot_delete_partner_referenced: "Cannot delete Partner because it is already referenced.",
    inactive_partner_confirmation: "Inactive Partner cannot be selected in new transactions but remains in history.",
    partner_information: "Partner Information",

    // Organization Module
    organization: "Organization",
    organization_code: "Organization Code",
    organization_name: "Organization Name",
    no_organization_message: "No organization defined. Create your first one.",
    no_matching_organization: "No matching organization found.",
    organization_details: "Organization Details",
    create_organization: "Create Organization",
    edit_organization: "Edit Organization",
    delete_organization: "Delete Organization",
    manage_organization: "Manage organization information",
    organization_code_exists: "Organization Code already exists. Please choose another.",
    organization_code_required: "Organization Code is required",
    organization_name_required: "Organization Name is required",
    cannot_delete_organization_referenced: "Cannot delete Organization because Branches are assigned.",
    inactive_organization_confirmation:
      "Inactive Organization will not be assignable to new branches but remains in history.",
    organization_information: "Organization Information",

    // Branch Module
    branch: "Branch",
    branch_code: "Branch Code",
    branch_name: "Branch Name",
    no_branch_message: "No branch defined. Create your first branch.",
    no_matching_branch: "No matching branch found.",
    branch_details: "Branch Details",
    create_branch: "Create Branch",
    edit_branch: "Edit Branch",
    delete_branch: "Delete Branch",
    manage_branch: "Manage branch information",
    branch_code_exists: "Branch Code already exists. Please choose another.",
    branch_code_required: "Branch Code is required",
    branch_name_required: "Branch Name is required",
    organization_required: "Branch must belong to an Organization",
    cannot_delete_branch_referenced: "Cannot delete Branch because Warehouses are assigned.",
    inactive_branch_confirmation: "Inactive Branch will not be assignable to new warehouses but remains in history.",
    branch_information: "Branch Information",
    select_organization: "Select Organization",

    // Warehouse Module
    warehouse: "Warehouse",
    warehouse_code: "Warehouse Code",
    warehouse_name: "Warehouse Name",
    no_warehouse_message: "No warehouse defined. Create your first warehouse.",
    no_matching_warehouse: "No matching warehouse found.",
    warehouse_details: "Warehouse Details",
    create_warehouse: "Create Warehouse",
    edit_warehouse: "Edit Warehouse",
    delete_warehouse: "Delete Warehouse",
    manage_warehouse: "Manage warehouse information",
    warehouse_code_exists: "Warehouse Code already exists. Please choose another.",
    warehouse_code_required: "Warehouse Code is required",
    warehouse_name_required: "Warehouse Name is required",
    branch_required: "Warehouse must belong to a Branch",
    cannot_delete_warehouse_referenced: "Cannot delete Warehouse because it is already in use.",
    inactive_warehouse_confirmation:
      "Inactive Warehouse will not be assignable to new transactions but remains in history.",
    warehouse_information: "Warehouse Information",
    select_branch: "Select Branch",

    // Goods Type Module
    goods_type: "Goods Type",
    goods_type_code: "Goods Type Code",
    goods_type_name: "Goods Type Name",
    no_goods_type_message: "No goods type defined. Create your first one.",
    no_matching_goods_type: "No matching goods type found.",
    goods_type_details: "Goods Type Details",
    create_goods_type: "Create Goods Type",
    edit_goods_type: "Edit Goods Type",
    delete_goods_type: "Delete Goods Type",
    manage_goods_type: "Manage goods type information",
    goods_type_code_exists: "Goods Type Code already exists. Please choose another.",
    goods_type_code_required: "Goods Type Code is required",
    goods_type_name_required: "Goods Type Name is required",
    cannot_delete_goods_type_referenced: "Cannot delete Goods Type because it is already referenced.",
    inactive_goods_type_confirmation: "Inactive Goods Type cannot be selected for new items but remains in history.",
    goods_type_information: "Goods Type Information",

    // Model Goods Module
    model_goods: "Model Goods",
    model_goods_name: "Model Goods Name",
    select_model_goods: "Select Model Goods",
    search_by_code_or_name: "Search by code or name...",
    tracking_type: "Tracking Type",
    item_code: "Item Code",
    item_name: "Item Name",
    no_model_goods_message: "No item defined. Create your first item.",
    no_matching_model_goods: "No matching item found.",
    model_goods_details: "Item Details",
    create_model_goods: "Create Item",
    edit_model_goods: "Edit Item",
    delete_model_goods: "Delete Item",
    manage_model_goods: "Manage item information",
    item_code_exists: "Item Code already exists. Please choose another.",
    item_code_required: "Item Code is required",
    item_name_required: "Item Name is required",
    goods_type_required: "Goods Type is required",
    primary_uom_required: "Please select Primary UoM (Base)",
    cannot_delete_model_goods_referenced: "Cannot delete Item because it is already referenced.",
    inactive_model_goods_confirmation: "Inactive Item cannot be used on new transactions but remains in history.",
    model_goods_information: "Item Information",
    general_information: "General Information",
    uom_conversions: "UoM & Conversions",
    tracking_shelf_life: "Tracking & Shelf-life",
    identification_attributes: "Identification & Attributes",
    primary_uom: "Primary UoM (Base)",
    allowed_uoms: "Allowed UoMs",
    tracking_type: "Tracking Type",
    tracking_none: "None",
    tracking_serial: "Serial",
    tracking_lot: "Lot",
    serial_input_mode: "Serial Input Mode",
    serial_single: "Single Add",
    serial_bulk: "Bulk Import from Excel",
    serial_pattern_hint: "Serial Pattern (Optional)",
    lot_number: "Lot Number",
    mfg_date: "MFG Date",
    exp_date: "EXP Date",
    shelf_life_days: "Shelf-life (Days)",
    expiry_policy: "Expiry Policy",
    fefo_recommended: "FEFO Recommended",
    sku: "SKU",
    barcode: "Barcode",
    brand: "Brand",
    model: "Model",
    variant: "Variant",
    dimensions: "Dimensions (L × W × H)",
    net_weight: "Net Weight",
    gross_weight: "Gross Weight",
    images: "Images",
    custom_attributes: "Custom Attributes",
    add_attribute: "Add Attribute",
    attribute_key: "Key",
    attribute_value: "Value",
    conversions_note: "Conversions are governed by UoM module",
    cannot_change_tracking: "Cannot change tracking because stock/history exists. Create a new item instead.",
    tracking_change_warning: "Changing tracking method will reset tracking configuration. Continue?",
    select_goods_type: "Select Goods Type",
    select_primary_uom: "Select Primary UoM",
    conversion_factor: "Conversion Factor",
    filter_by_goods_type: "Filter by Goods Type",
    filter_by_tracking: "Filter by Tracking",

    // Location Module
    location_code: "Location Code",
    location_name: "Location Name",
    location_type: "Location Type",
    location_type_storage: "Storage",
    location_type_picking: "Picking",
    location_type_receiving: "Receiving",
    location_type_shipping: "Shipping",
    location_type_other: "Other",
    allowed_goods_type: "Allowed Goods Type",
    restricted_goods_type: "Restricted Goods Type",
    no_location_message: "No location defined. Create your first location.",
    location_details: "Location Details",
    create_location: "Create Location",
    edit_location: "Edit Location",
    delete_location: "Delete Location",
    location_code_required: "Location Code is required",
    location_name_required: "Location Name is required",
    warehouse_required: "Warehouse is required",
    location_code_exists_in_warehouse: "Location Code already exists in this Warehouse",
    cannot_delete_location_in_use: "Cannot delete Location because it is already in use",
    location_created_successfully: "Location created successfully",
    location_updated_successfully: "Location updated successfully",
    location_deleted_successfully: "Location deleted successfully",
    manage_warehouse_locations: "Manage warehouse storage locations",
    filter_by_warehouse: "Filter by Warehouse",
    filter_by_location_type: "Filter by Location Type",
    all_warehouses: "All Warehouses",
    all_location_types: "All Location Types",
    all_status: "All Status",
    select_warehouse: "Select Warehouse",
    goods_type_conflict: "Goods Type cannot be in both Allowed and Restricted lists",
    allowed_goods_type_note: "Leave empty to allow all goods types",
    restricted_goods_type_note: "Goods types not allowed in this location",
    all_goods_types: "All goods types allowed",
    none: "None",
    search_goods_type: "Search goods type...",
    no_goods_type_found: "No goods type found",
    already_in_restricted: "Already in Restricted list",
    already_in_allowed: "Already in Allowed list",
    create_new_location: "Create a new location",
    edit_location_information: "Edit location information",
    enter_location_code: "Enter location code",
    confirm_status_change: "Confirm Status Change",
    inactive_location_warning: "Inactive Location cannot be assigned in new transactions but remains in history",
    confirm: "Confirm",
    please_fix_errors: "Please fix validation errors",
    export_started: "Export started successfully",
    status_changed: "Status changed",

    // Stock Onhand Module
    stock_onhand_title: "Stock Onhand",
    current_stock_snapshot: "Current stock snapshot at",
    item_code: "Item Code",
    item_name: "Item Name",
    goods_type: "Goods Type",
    tracking: "Tracking",
    uom_base: "UoM (Base)",
    onhand: "Onhand",
    allocated: "Allocated",
    available: "Available",
    last_movement: "Last Movement",
    low_stock: "Low Stock",
    near_expiry: "Near Expiry",
    expired: "Expired",
    negative_stock: "Negative Stock",
    active_only: "Active Only",
    display_uom: "Display UoM",
    exp_range: "Expiry Range",
    has_negative: "Has Negative",
    reset_filters: "Reset Filters",
    apply_filters: "Apply Filters",
    summary: "Summary",
    summary_no_tracking: "Summary (No Tracking)",
    read_only_base_uom: "Read-only in Base UoM",
    open_stock_card: "View Stock Card",
    serials: "Serials",
    serial_no: "Serial No",
    received_date: "Received Date",
    received_by: "Received By",
    lots: "Lots",
    lot_no: "Lot No",
    mfg_date: "MFG Date",
    exp_date: "EXP Date",
    serial_detail: "Serial Detail",
    lot_detail: "Lot Detail",
    stock_card: "Stock Card",
    movement_at: "Movement Date",
    doc_type: "Document Type",
    ref_no: "Reference No",
    in_qty: "In Qty",
    out_qty: "Out Qty",
    balance: "Balance",
    loc_from_to: "From/To Location",
    performed_by: "Performed By",
    no_onhand_records: "No onhand records found",
    no_serials_found: "No serials found",
    no_lots_found: "No lots found",
    select_item: "Select Item",
    near_expiry_days: "EXP ≤ N days",
    hold: "Hold",
    blocked: "Blocked",
    available_status: "Available",
    open_stock_card_serial: "View Stock Card (this Serial)",
    open_stock_card_lot: "View Stock Card (this Lot)",
    request_adjustment: "Request Adjustment",
    filters: "Filters",
    advanced_filters: "Advanced Filters",
    show_advanced: "Show Advanced",
    hide_advanced: "Hide Advanced",
    all: "All",
    no_items_found: "No items found",
    double_click_to_view_details: "Double-click row to view details",
    item_details: "Item Details",
    close: "Close",
    last_movement_by: "Last Movement By",
    contains: "Contains",
    include_zero_stock: "Include Zero Stock",
    columns: "Columns",
    notes: "Notes",

    // Goods Receipt Module
    goods_receipt: "Goods Receipt",
    goods_receipt_title: "Goods Receipt",
    receipt_no: "Receipt No",
    receipt_type: "Receipt Type",
    ref_no: "Reference No",
    partner: "Partner",
    destination_warehouse: "Destination Warehouse",
    receipt_type_po: "PO Receipt",
    receipt_type_return: "Return",
    receipt_type_transfer_in: "Transfer In",
    receipt_type_other: "Other",
    draft: "Draft",
    receiving: "Receiving",
    completed: "Completed",
    cancelled: "Cancelled",
    no_receipts_message: "No receipts yet. Create your first Goods Receipt.",
    no_matching_receipts: "No matching receipts found.",
    receipt_details: "Receipt Details",
    create_receipt: "Create Receipt",
    edit_receipt: "Edit Receipt",
    cancel_receipt: "Cancel Receipt",
    print_receipt: "Print Receipt",
    copy_receipt: "Copy Receipt",
    manage_goods_receipt: "Manage goods receipt documents",
    date_range: "Date Range",
    from_date: "From Date",
    to_date: "To Date",
    print: "Print",
    copy: "Copy",
    double_click_to_view_receipt: "Double-click row to view receipt details",
    receipt_created_successfully: "Receipt created successfully",
    receipt_updated_successfully: "Receipt updated successfully",
    receipt_cancelled_successfully: "Receipt cancelled successfully",
    confirm_cancel_receipt: "Are you sure you want to cancel this receipt?",
    cannot_edit_completed: "Cannot edit completed receipt",
    cannot_cancel_completed: "Cannot cancel completed receipt",
    goods_receipt_no: "Goods Receipt No",
    goods_receipt_type: "Goods Receipt Type",
    expected_receipt_date: "Expected Receipt Date",
    auto_generated: "Auto-generated",
    enter_note: "Enter note",
    information: "Information",
    receipt_plan: "Receipt Plan",
    model_asset: "Model Asset",
    model_asset_name: "Model Asset Name",
    qty_planned: "Qty Planned",
    import: "Import",
    export: "Export",
    create: "Create",
    total_item: "Total Item",
    no_receipt_lines: "No receipt lines added yet",
    import_feature_coming_soon: "Import feature coming soon",
    export_feature_coming_soon: "Export feature coming soon",
    add_line_feature_coming_soon: "Add line feature coming soon",
    no_data_to_export: "No data to export",
    goods_receipt_saved: "Goods receipt saved successfully",
    goods_receipt_created: "Goods receipt created successfully",
    goods_transfer_information: "Goods transfer information",
    created_date: "Created date",
    handler: "Handler",
    approved_by: "Approved By",
    approved_date: "Approved Date",
    status_history: "Status history",
    no_status_history: "No status history available",
    receipt_lines: "Receipt Lines",
    planned_quantity: "Planned Quantity",
    quantity_entered: "Quantity entered",
    diff_quantity: "Diff Quantity",
    detail: "Detail",
    view_line_detail: "View line detail",
    destination_warehouse_required: "Destination warehouse is required",
    warehouse_not_active: "Selected warehouse is not active",
    ref_no_required_for_po_transfer: "Reference number is required for PO/Transfer receipts",
    at_least_one_line_required: "At least one line is required",
    line: "Line",
    serial_count_must_match_qty: "Serial count must match quantity",
    lot_qty_must_match_total_qty: "Lot quantity must match total quantity",
    goods_receipt_saved_as_draft: "Goods receipt saved as draft",
    line_no: "Line No",
    qty_received: "Qty Received",
    diff: "Diff",
    line_deleted: "Line deleted successfully",
    doc_date: "Document Date",
    enter_reference_number: "Enter reference number",
    select_partner: "Select partner",
    add_line: "Add Line",
    model: "Model",
    select_model: "Select model",
    unit: "Unit",
    qty: "Quantity",
    location: "Location",
    select_location: "Select location",
    unit_price: "Unit Price",
    optional: "Optional",
    notes: "Notes",
    general: "General",
    serial_manager: "Serial Manager",
    lot_manager: "Lot Manager",
    attachments: "Attachments",
    serial_numbers: "Serial Numbers",
    captured: "Captured",
    required: "Required",
    need_more_serials: "Need more serials",
    enter_serial_number: "Enter serial number",
    add: "Add",
    bulk_paste: "Bulk Paste",
    paste_serials_one_per_line: "Paste serial numbers (one per line)",
    serials_added: "serials added",
    serial_cannot_be_empty: "Serial number cannot be empty",
    serial_already_exists: "Serial number already exists",
    lot_information: "Lot Information",
    total_lot_qty: "Total Lot Qty",
    need_more_lot_qty: "Need more lot quantity",
    lot_no_required: "Lot number is required",
    lot_qty_must_be_greater_than_zero: "Lot quantity must be greater than zero",
    lot_added: "Lot added successfully",
    lot: "Lot",
    expiry_date_cannot_be_past: "Expiry date cannot be in the past",
    add_lot: "Add Lot",
    expired: "Expired",
    line_attachments: "Line Attachments",
    attach_files_to_this_line: "Attach files to this line",
    upload_files: "Upload Files",
    files_uploaded: "files uploaded",
    no_attachments_yet: "No attachments yet",
    save_line: "Save Line",
    item_required: "Item is required",
    qty_must_be_greater_than_zero: "Quantity must be greater than zero",
    at_least_one_lot_required: "At least one lot is required",
    line_saved: "Line saved successfully",
    view_line: "View Line",
    edit_line: "Edit Line",
    view_receipt_line_details: "View receipt line details",
    edit_receipt_line_details: "Edit receipt line details",
    approve: "Approve",
    reject: "Reject",
    approve_goods_receipt: "Approve Goods Receipt",
    approve_goods_receipt_confirmation: "Are you sure you want to approve this goods receipt?",
    reject_goods_receipt: "Reject Goods Receipt",
    reject_goods_receipt_confirmation: "Are you sure you want to reject this goods receipt?",
    cancel_goods_receipt: "Cancel Goods Receipt",
    cancel_goods_receipt_confirmation: "Are you sure you want to cancel this goods receipt?",
    goods_receipt_approved: "Goods receipt approved successfully",
    goods_receipt_rejected: "Goods receipt rejected successfully",
    goods_receipt_cancelled: "Goods receipt cancelled successfully",
    import_successful: "Import successful",
    export_successful: "Export successful",
    enter_lot_number: "Enter lot number",
    search_model: "Search model...",
    no_models_found: "No models found",
    edit_details: "Edit Details",
    select_model_first: "Select model first",
    fill_required_fields_first: "Fill required fields first (Warehouse, Ref No for PO/Transfer)",
    qty_exceeds_onhand: "Quantity cannot exceed onhand quantity",
  },
  vi: {
    // Header
    notifications: "Thông báo",
    profile: "Hồ sơ",
    logout: "Đăng xuất",

    // Menu
    dashboard: "Tổng quan",
    warehouse_operations: "Vận hành kho",
    stock_onhand: "Tồn kho",
    goods_receipt: "Nhập kho",
    goods_issue: "Xuất kho",
    inventory_count: "Kiểm kê",
    goods_transfer: "Chuyển kho",
    putaway: "Lưu kho",
    master_data: "Dữ liệu gốc",
    uom: "Đơn vị tính",
    partner: "Đối tác",
    organization: "Tổ chức",
    branch: "Chi nhánh",
    warehouse: "Kho",
    location: "Vị trí",
    goods_management: "Quản lý hàng hóa",
    goods_type: "Loại hàng",
    model_goods: "Mã hàng hóa",
    reports: "Báo cáo",
    authentication: "Xác thực",

    // Table
    search: "Tìm kiếm",
    filter: "Lọc",
    export_excel: "Xuất Excel",
    import_excel: "Nhập Excel",
    column_visibility: "Hiển thị cột",
    showing: "Hiển thị",
    of: "trên",
    entries: "bản ghi",
    page: "Trang",

    // Actions
    add_new: "Thêm mới",
    edit: "Sửa",
    delete: "Xóa",
    save: "Lưu",
    save_close: "Lưu & Đóng",
    cancel: "Hủy",
    confirm: "Xác nhận",
    back: "Quay lại",
    view_details: "Xem chi tiết",

    // Footer
    copyright: "© 2025 Delfi Tri Nguyen. Bản quyền đã được bảo hộ.",
    version: "Phiên bản: 1.0.1",

    // Common
    created_by: "Tạo bởi",
    created_at: "Ngày tạo",
    updated_by: "Sửa bởi",
    updated_at: "Ngày sửa",
    status: "Trạng thái",
    actions: "Thao tác",
    code: "Mã",
    name: "Tên",
    description: "Mô tả",

    // UoM Module
    uom_code: "Mã đơn vị",
    uom_name: "Tên đơn vị",
    measurement_type: "Loại đo lường",
    uom_type: "Loại đơn vị",
    base_uom: "Đơn vị cơ sở",
    conversion_factor: "Hệ số quy đổi",
    active: "Hoạt động",
    inactive: "Ngừng hoạt động",
    base: "Cơ sở",
    alt: "Phụ",
    piece: "Cái",
    weight: "Khối lượng",
    volume: "Thể tích",
    length: "Chiều dài",
    area: "Diện tích",
    time: "Thời gian",
    no_uom_message: "Chưa có đơn vị tính nào. Hãy tạo đơn vị đầu tiên.",
    no_results_message: "Không tìm thấy kết quả.",
    uom_details: "Chi tiết đơn vị",
    create_uom: "Tạo đơn vị tính",
    edit_uom: "Sửa đơn vị tính",
    delete_uom: "Xóa đơn vị tính",
    confirm_delete: "Xác nhận xóa",
    type_code_to_confirm: "Nhập mã đơn vị để xác nhận xóa",
    cannot_delete_referenced: "Không thể xóa đơn vị tính vì đã được tham chiếu.",
    select_base_uom: "Vui lòng chọn đơn vị cơ sở (Mỗi nhóm phải có đúng 1 đơn vị cơ sở).",
    conversion_factor_greater_zero: "Hệ số quy đổi phải lớn hơn 0.",
    cannot_have_multiple_bases: "Không thể gán nhiều hơn 1 đơn vị cơ sở cho mỗi nhóm.",
    inactive_confirmation: "Đơn vị ngừng hoạt động không thể dùng cho giao dịch mới nhưng vẫn giữ trong lịch sử.",
    audit_information: "Thông tin kiểm toán",
    manage_uom: "Quản lý định nghĩa đơn vị đo lường",
    uom_required: "Mã đơn vị là bắt buộc",
    name_required: "Tên đơn vị là bắt buộc",
    measurement_type_required: "Loại đo lường là bắt buộc",
    uom_type_required: "Loại đơn vị là bắt buộc",
    code_must_be_unique: "Mã đơn vị phải là duy nhất",
    required: "Bắt buộc",
    view: "Xem",
    delete_confirmation_message: "Bạn có chắc chắn muốn xóa đơn vị tính này? Hành động này không thể hoàn tác.",

    // Partner Module
    partner_code: "Mã đối tác",
    partner_name: "Tên đối tác",
    partner_type: "Loại đối tác",
    tax_code: "Mã số thuế",
    phone: "Số điện thoại",
    email: "Email",
    address: "Địa chỉ",
    contact_person: "Người liên hệ",
    customer: "Khách hàng",
    supplier: "Nhà cung cấp",
    carrier: "Đơn vị vận chuyển",
    other: "Khác",
    no_partner_message: "Chưa có đối tác nào. Hãy tạo đối tác đầu tiên.",
    no_matching_partner: "Không tìm thấy đối tác phù hợp.",
    partner_details: "Chi tiết đối tác",
    create_partner: "Tạo đối tác",
    edit_partner: "Sửa đối tác",
    delete_partner: "Xóa đối tác",
    manage_partner: "Quản lý thông tin đối tác",
    partner_code_exists: "Mã đối tác đã tồn tại. Vui lòng chọn mã khác.",
    partner_code_required: "Mã đối tác là bắt buộc",
    partner_name_required: "Tên đối tác là bắt buộc",
    invalid_email: "Định dạng email không hợp lệ",
    invalid_phone: "Định dạng số điện thoại không hợp lệ",
    cannot_delete_partner_referenced: "Không thể xóa đối tác vì đã được tham chiếu.",
    inactive_partner_confirmation:
      "Đối tác ngừng hoạt động không thể chọn cho giao dịch mới nhưng vẫn giữ trong lịch sử.",
    partner_information: "Thông tin đối tác",

    // Organization Module
    organization: "Tổ chức",
    organization_code: "Mã tổ chức",
    organization_name: "Tên tổ chức",
    no_organization_message: "Chưa có tổ chức nào. Hãy tạo tổ chức đầu tiên.",
    no_matching_organization: "Không tìm thấy tổ chức phù hợp.",
    organization_details: "Chi tiết tổ chức",
    create_organization: "Tạo tổ chức",
    edit_organization: "Sửa tổ chức",
    delete_organization: "Xóa tổ chức",
    manage_organization: "Quản lý thông tin tổ chức",
    organization_code_exists: "Mã tổ chức đã tồn tại. Vui lòng chọn mã khác.",
    organization_code_required: "Mã tổ chức là bắt buộc",
    organization_name_required: "Tên tổ chức là bắt buộc",
    cannot_delete_organization_referenced: "Không thể xóa tổ chức vì đã có chi nhánh được gán.",
    inactive_organization_confirmation:
      "Tổ chức ngừng hoạt động sẽ không thể gán cho chi nhánh mới nhưng vẫn giữ trong lịch sử.",
    organization_information: "Thông tin tổ chức",

    // Branch Module
    branch: "Chi nhánh",
    branch_code: "Mã chi nhánh",
    branch_name: "Tên chi nhánh",
    no_branch_message: "Chưa có chi nhánh nào. Hãy tạo chi nhánh đầu tiên.",
    no_matching_branch: "Không tìm thấy chi nhánh phù hợp.",
    branch_details: "Chi tiết chi nhánh",
    create_branch: "Tạo chi nhánh",
    edit_branch: "Sửa chi nhánh",
    delete_branch: "Xóa chi nhánh",
    manage_branch: "Quản lý thông tin chi nhánh",
    branch_code_exists: "Mã chi nhánh đã tồn tại. Vui lòng chọn mã khác.",
    branch_code_required: "Mã chi nhánh là bắt buộc",
    branch_name_required: "Tên chi nhánh là bắt buộc",
    organization_required: "Chi nhánh phải thuộc về một tổ chức",
    cannot_delete_branch_referenced: "Không thể xóa chi nhánh vì đã có kho được gán.",
    inactive_branch_confirmation: "Chi nhánh ngừng hoạt động sẽ không thể gán cho kho mới nhưng vẫn giữ trong lịch sử.",
    branch_information: "Thông tin chi nhánh",
    select_organization: "Chọn tổ chức",

    // Warehouse Module
    warehouse: "Kho",
    warehouse_code: "Mã kho",
    warehouse_name: "Tên kho",
    no_warehouse_message: "Chưa có kho nào. Hãy tạo kho đầu tiên.",
    no_matching_warehouse: "Không tìm thấy kho phù hợp.",
    warehouse_details: "Chi tiết kho",
    create_warehouse: "Tạo kho",
    edit_warehouse: "Sửa kho",
    delete_warehouse: "Xóa kho",
    manage_warehouse: "Quản lý thông tin kho",
    warehouse_code_exists: "Mã kho đã tồn tại. Vui lòng chọn mã khác.",
    warehouse_code_required: "Mã kho là bắt buộc",
    warehouse_name_required: "Tên kho là bắt buộc",
    branch_required: "Kho phải thuộc về một chi nhánh",
    cannot_delete_warehouse_referenced: "Không thể xóa kho vì đã được sử dụng.",
    inactive_warehouse_confirmation:
      "Kho ngừng hoạt động sẽ không thể gán cho giao dịch mới nhưng vẫn giữ trong lịch sử.",
    warehouse_information: "Thông tin kho",
    select_branch: "Chọn chi nhánh",

    // Goods Type Module
    goods_type: "Loại hàng",
    goods_type_code: "Mã loại hàng",
    goods_type_name: "Tên loại hàng",
    no_goods_type_message: "Chưa có loại hàng nào. Hãy tạo loại hàng đầu tiên.",
    no_matching_goods_type: "Không tìm thấy loại hàng phù hợp.",
    goods_type_details: "Chi tiết loại hàng",
    create_goods_type: "Tạo loại hàng",
    edit_goods_type: "Sửa loại hàng",
    delete_goods_type: "Xóa loại hàng",
    manage_goods_type: "Quản lý thông tin loại hàng",
    goods_type_code_exists: "Mã loại hàng đã tồn tại. Vui lòng chọn mã khác.",
    goods_type_code_required: "Mã loại hàng là bắt buộc",
    goods_type_name_required: "Tên loại hàng là bắt buộc",
    cannot_delete_goods_type_referenced: "Không thể xóa loại hàng vì đã được tham chiếu.",
    inactive_goods_type_confirmation:
      "Loại hàng ngừng hoạt động không thể chọn cho sản phẩm mới nhưng vẫn giữ trong lịch sử.",
    goods_type_information: "Thông tin loại hàng",

    // Model Goods Module
    model_goods: "Mã hàng hóa",
    model_goods_name: "Tên hàng hóa",
    select_model_goods: "Chọn hàng hóa",
    search_by_code_or_name: "Tìm theo mã hoặc tên...",
    tracking_type: "Loại truy xuất",
    item_code: "Mã hàng",
    item_name: "Tên hàng",
    no_model_goods_message: "Chưa có hàng hóa nào. Hãy tạo hàng hóa đầu tiên.",
    no_matching_model_goods: "Không tìm thấy hàng hóa phù hợp.",
    model_goods_details: "Chi tiết hàng hóa",
    create_model_goods: "Tạo hàng hóa",
    edit_model_goods: "Sửa hàng hóa",
    delete_model_goods: "Xóa hàng hóa",
    manage_model_goods: "Quản lý thông tin hàng hóa",
    item_code_exists: "Mã hàng đã tồn tại. Vui lòng chọn mã khác.",
    item_code_required: "Mã hàng là bắt buộc",
    item_name_required: "Tên hàng là bắt buộc",
    goods_type_required: "Loại hàng là bắt buộc",
    primary_uom_required: "Vui lòng chọn đơn vị tính chính (Base)",
    cannot_delete_model_goods_referenced: "Không thể xóa hàng hóa vì đã được tham chiếu.",
    inactive_model_goods_confirmation:
      "Hàng hóa ngừng hoạt động không thể sử dụng cho giao dịch mới nhưng vẫn giữ trong lịch sử.",
    model_goods_information: "Thông tin hàng hóa",
    general_information: "Thông tin chung",
    uom_conversions: "Đơn vị tính & Quy đổi",
    tracking_shelf_life: "Truy xuất & Hạn sử dụng",
    identification_attributes: "Định danh & Thuộc tính",
    primary_uom: "ĐVT chính (Base)",
    allowed_uoms: "ĐVT cho phép",
    tracking_type: "Loại truy xuất",
    tracking_none: "Không",
    tracking_serial: "Serial",
    tracking_lot: "Lô",
    serial_input_mode: "Chế độ nhập Serial",
    serial_single: "Nhập đơn",
    serial_bulk: "Nhập hàng loạt từ Excel",
    serial_pattern_hint: "Mẫu Serial (Tùy chọn)",
    lot_number: "Số lô",
    mfg_date: "Ngày SX",
    exp_date: "Ngày HSD",
    shelf_life_days: "Thời hạn sử dụng (Ngày)",
    expiry_policy: "Chính sách hết hạn",
    fefo_recommended: "Khuyến nghị FEFO",
    sku: "SKU",
    barcode: "Mã vạch",
    brand: "Thương hiệu",
    model: "Model",
    variant: "Phiên bản",
    dimensions: "Kích thước (D × R × C)",
    net_weight: "Trọng lượng tịnh",
    gross_weight: "Trọng lượng gộp",
    images: "Hình ảnh",
    custom_attributes: "Thuộc tính tùy chỉnh",
    add_attribute: "Thêm thuộc tính",
    attribute_key: "Tên thuộc tính",
    attribute_value: "Giá trị",
    conversions_note: "Quy đổi được quản lý bởi module ĐVT",
    cannot_change_tracking:
      "Không thể thay đổi phương thức truy xuất vì đã có tồn kho/lịch sử. Vui lòng tạo hàng hóa mới.",
    tracking_change_warning: "Thay đổi phương thức truy xuất sẽ xóa cấu hình hiện tại. Tiếp tục?",
    select_goods_type: "Chọn loại hàng",
    select_primary_uom: "Chọn ĐVT chính",
    conversion_factor: "Hệ số quy đổi",
    filter_by_goods_type: "Lọc theo loại hàng",
    filter_by_tracking: "Lọc theo truy xuất",

    // Location Module
    location_code: "Mã vị trí",
    location_name: "Tên vị trí",
    location_type: "Loại vị trí",
    location_type_storage: "Khu lưu trữ",
    location_type_picking: "Khu lấy hàng",
    location_type_receiving: "Khu nhận hàng",
    location_type_shipping: "Khu xuất hàng",
    location_type_other: "Khác",
    allowed_goods_type: "Loại hàng cho phép",
    restricted_goods_type: "Loại hàng hạn chế",
    no_location_message: "Chưa có vị trí nào. Tạo vị trí đầu tiên.",
    location_details: "Chi tiết vị trí",
    create_location: "Tạo vị trí",
    edit_location: "Sửa vị trí",
    delete_location: "Xóa vị trí",
    location_code_required: "Mã vị trí là bắt buộc",
    location_name_required: "Tên vị trí là bắt buộc",
    warehouse_required: "Kho là bắt buộc",
    location_code_exists_in_warehouse: "Mã vị trí đã tồn tại trong kho này",
    cannot_delete_location_in_use: "Không thể xóa vị trí vì đang được sử dụng",
    location_created_successfully: "Tạo vị trí thành công",
    location_updated_successfully: "Cập nhật vị trí thành công",
    location_deleted_successfully: "Xóa vị trí thành công",
    manage_warehouse_locations: "Quản lý vị trí lưu kho",
    filter_by_warehouse: "Lọc theo kho",
    filter_by_location_type: "Lọc theo loại vị trí",
    all_warehouses: "Tất cả kho",
    all_location_types: "Tất cả loại vị trí",
    all_status: "Tất cả trạng thái",
    select_warehouse: "Chọn kho",
    goods_type_conflict: "Loại hàng không thể nằm trong cả hai danh sách Cho phép và Hạn chế",
    allowed_goods_type_note: "Để trống để cho phép tất cả loại hàng",
    restricted_goods_type_note: "Các loại hàng không được phép tại vị trí này",
    all_goods_types: "Cho phép tất cả loại hàng",
    none: "Không",
    search_goods_type: "Tìm kiếm loại hàng...",
    no_goods_type_found: "Không tìm thấy loại hàng",
    already_in_restricted: "Đã có trong danh sách Hạn chế",
    already_in_allowed: "Đã có trong danh sách Cho phép",
    create_new_location: "Tạo vị trí mới",
    edit_location_information: "Sửa thông tin vị trí",
    enter_location_code: "Nhập mã vị trí",
    confirm_status_change: "Xác nhận thay đổi trạng thái",
    inactive_location_warning:
      "Vị trí Inactive không được phân công trong giao dịch mới nhưng vẫn tồn tại trong lịch sử",
    confirm: "Xác nhận",
    please_fix_errors: "Vui lòng sửa các lỗi",
    export_started: "Bắt đầu xuất dữ liệu thành công",
    status_changed: "Đã thay đổi trạng thái",

    // Stock Onhand Module
    stock_onhand_title: "Tồn kho hiện tại",
    current_stock_snapshot: "Trạng thái tồn kho tại thời điểm",
    item_code: "Mã hàng",
    item_name: "Tên hàng",
    goods_type: "Loại hàng",
    tracking: "Truy xuất",
    uom_base: "Đơn vị (Base)",
    onhand: "Tồn",
    allocated: "Đã giữ",
    available: "Khả dụng",
    last_movement: "Biến động gần nhất",
    low_stock: "Tồn thấp",
    near_expiry: "Gần hết hạn",
    expired: "Hết hạn",
    negative_stock: "Tồn âm",
    active_only: "Chỉ Active",
    display_uom: "Đơn vị hiển thị",
    exp_range: "Khoảng HSD",
    has_negative: "Có tồn âm",
    reset_filters: "Đặt lại bộ lọc",
    apply_filters: "Áp dụng",
    summary: "Tổng quan",
    summary_no_tracking: "Tổng quan (Không tracking)",
    read_only_base_uom: "Chỉ xem, đơn vị Base",
    open_stock_card: "Xem thẻ kho",
    serials: "Serial",
    serial_no: "Số Serial",
    received_date: "Ngày nhập",
    received_by: "Người nhập",
    lots: "Lô",
    lot_no: "Số lô",
    mfg_date: "Ngày SX",
    exp_date: "Hạn sử dụng",
    serial_detail: "Chi tiết Serial",
    lot_detail: "Chi tiết Lô",
    stock_card: "Thẻ kho",
    movement_at: "Ngày biến động",
    doc_type: "Loại chứng từ",
    ref_no: "Số tham chiếu",
    in_qty: "SL nhập",
    out_qty: "SL xuất",
    balance: "Tồn",
    loc_from_to: "Từ/Đến vị trí",
    performed_by: "Người thực hiện",
    no_onhand_records: "Không có dữ liệu tồn kho",
    no_serials_found: "Không có serial",
    no_lots_found: "Không có lô phù hợp",
    select_item: "Chọn hàng hóa",
    near_expiry_days: "Hạn sử dụng ≤ N ngày",
    hold: "Giữ",
    blocked: "Khóa",
    available_status: "Có sẵn",
    open_stock_card_serial: "Xem thẻ kho (Serial này)",
    open_stock_card_lot: "Xem thẻ kho (Lô này)",
    request_adjustment: "Yêu cầu điều chỉnh",
    filters: "Bộ lọc",
    advanced_filters: "Bộ lọc nâng cao",
    show_advanced: "Hiện nâng cao",
    hide_advanced: "Ẩn nâng cao",
    all: "Tất cả",
    no_items_found: "Không tìm thấy",
    double_click_to_view_details: "Nhấp đúp vào dòng để xem chi tiết",
    item_details: "Chi tiết hàng hóa",
    close: "Đóng",
    last_movement_by: "Người biến động cuối",
    contains: "Chứa",
    include_zero_stock: "Bao gồm tồn bằng 0",
    columns: "Cột hiển thị",
    notes: "Ghi chú",

    // Goods Receipt Module
    goods_receipt: "Nhập kho",
    goods_receipt_title: "Nhập kho",
    receipt_no: "Số phiếu nhập",
    receipt_type: "Loại phiếu",
    ref_no: "Số tham chiếu",
    partner: "Đối tác",
    destination_warehouse: "Kho đích",
    receipt_type_po: "Nhập theo PO",
    receipt_type_return: "Nhập trả lại",
    receipt_type_transfer_in: "Nhập chuyển kho",
    receipt_type_other: "Nhập khác",
    draft: "Nháp",
    receiving: "Đang nhập",
    completed: "Hoàn thành",
    cancelled: "Đã hủy",
    no_receipts_message: "Chưa có phiếu nhập nào. Tạo phiếu nhập đầu tiên.",
    no_matching_receipts: "Không tìm thấy phiếu nhập phù hợp.",
    receipt_details: "Chi tiết phiếu nhập",
    create_receipt: "Tạo phiếu nhập",
    edit_receipt: "Sửa phiếu nhập",
    cancel_receipt: "Hủy phiếu nhập",
    print_receipt: "In phiếu nhập",
    copy_receipt: "Sao chép phiếu",
    manage_goods_receipt: "Quản lý chứng từ nhập kho",
    date_range: "Khoảng thời gian",
    from_date: "Từ ngày",
    to_date: "Đến ngày",
    print: "In",
    copy: "Sao chép",
    double_click_to_view_receipt: "Nhấp đúp vào dòng để xem chi tiết phiếu nhập",
    receipt_created_successfully: "Tạo phiếu nhập thành công",
    receipt_updated_successfully: "Cập nhật phiếu nhập thành công",
    receipt_cancelled_successfully: "Hủy phiếu nhập thành công",
    confirm_cancel_receipt: "Bạn có chắc muốn hủy phiếu nhập này?",
    cannot_edit_completed: "Không thể sửa phiếu đã hoàn thành",
    cannot_cancel_completed: "Không thể hủy phiếu đã hoàn thành",
    goods_receipt_no: "Số phiếu nhập kho",
    goods_receipt_type: "Loại phiếu nhập kho",
    expected_receipt_date: "Ngày dự kiến nhập",
    auto_generated: "Tự động tạo",
    enter_note: "Nhập ghi chú",
    information: "Thông tin",
    receipt_plan: "Kế hoạch nhập",
    model_asset: "Mã tài sản",
    model_asset_name: "Tên tài sản",
    qty_planned: "SL dự kiến",
    import: "Nhập",
    export: "Xuất",
    create: "Tạo",
    total_item: "Tổng số lượng",
    no_receipt_lines: "Chưa có dòng nhập kho",
    import_feature_coming_soon: "Tính năng nhập sắp ra mắt",
    export_feature_coming_soon: "Tính năng xuất sắp ra mắt",
    add_line_feature_coming_soon: "Tính năng thêm dòng sắp ra mắt",
    no_data_to_export: "Không có dữ liệu để xuất",
    goods_receipt_saved: "Lưu phiếu nhập kho thành công",
    goods_receipt_created: "Tạo phiếu nhập kho thành công",
    goods_transfer_information: "Thông tin chuyển hàng",
    created_date: "Ngày tạo",
    handler: "Người xử lý",
    approved_by: "Người duyệt",
    approved_date: "Ngày duyệt",
    status_history: "Lịch sử trạng thái",
    no_status_history: "Không có lịch sử trạng thái",
    receipt_lines: "Dòng nhập kho",
    planned_quantity: "SL dự kiến",
    quantity_entered: "SL đã nhập",
    diff_quantity: "SL chênh lệch",
    detail: "Chi tiết",
    view_line_detail: "Xem chi tiết dòng",
    destination_warehouse_required: "Kho đích là bắt buộc",
    warehouse_not_active: "Kho đã chọn không hoạt động",
    ref_no_required_for_po_transfer: "Số tham chiếu là bắt buộc cho phiếu PO/Chuyển kho",
    at_least_one_line_required: "Cần ít nhất một dòng",
    line: "Dòng",
    serial_count_must_match_qty: "Số lượng serial phải khớp với số lượng",
    lot_qty_must_match_total_qty: "Tổng số lượng lô phải khớp với số lượng",
    goods_receipt_saved_as_draft: "Lưu phiếu nhập kho dạng nháp thành công",
    line_no: "Số dòng",
    qty_received: "SL đã nhập",
    diff: "Chênh lệch",
    line_deleted: "Xóa dòng thành công",
    doc_date: "Ngày chứng từ",
    enter_reference_number: "Nhập số tham chiếu",
    select_partner: "Chọn đối tác",
    add_line: "Thêm dòng",
    model: "Mô hình",
    select_model: "Chọn mô hình",
    unit: "Đơn vị",
    qty: "Số lượng",
    location: "Vị trí",
    select_location: "Chọn vị trí",
    unit_price: "Đơn giá",
    optional: "Tùy chọn",
    notes: "Ghi chú",
    general: "Chung",
    serial_manager: "Quản lý Serial",
    lot_manager: "Quản lý Lô",
    attachments: "Tệp đính kèm",
    serial_numbers: "Số Serial",
    captured: "Đã nhập",
    required: "Yêu cầu",
    need_more_serials: "Cần thêm serial",
    enter_serial_number: "Nhập số serial",
    add: "Thêm",
    bulk_paste: "Dán hàng loạt",
    paste_serials_one_per_line: "Dán số serial (mỗi dòng một số)",
    serials_added: "serial đã thêm",
    serial_cannot_be_empty: "Số serial không được để trống",
    serial_already_exists: "Số serial đã tồn tại",
    lot_information: "Thông tin lô",
    total_lot_qty: "Tổng SL lô",
    need_more_lot_qty: "Cần thêm số lượng lô",
    lot_no_required: "Số lô là bắt buộc",
    lot_qty_must_be_greater_than_zero: "Số lượng lô phải lớn hơn 0",
    lot_added: "Thêm lô thành công",
    lot: "Lô",
    expiry_date_cannot_be_past: "Ngày hết hạn không thể là quá khứ",
    add_lot: "Thêm lô",
    expired: "Hết hạn",
    line_attachments: "Tệp đính kèm dòng",
    attach_files_to_this_line: "Đính kèm tệp cho dòng này",
    upload_files: "Tải lên tệp",
    files_uploaded: "tệp đã tải lên",
    no_attachments_yet: "Chưa có tệp đính kèm",
    save_line: "Lưu dòng",
    item_required: "Hàng hóa là bắt buộc",
    qty_must_be_greater_than_zero: "Số lượng phải lớn hơn 0",
    at_least_one_lot_required: "Cần ít nhất một lô",
    line_saved: "Lưu dòng thành công",
    view_line: "Xem dòng",
    edit_line: "Sửa dòng",
    view_receipt_line_details: "Xem chi tiết dòng nhập",
    edit_receipt_line_details: "Sửa chi tiết dòng nhập",
    approve: "Duyệt",
    reject: "Từ chối",
    approve_goods_receipt: "Duyệt phiếu nhập kho",
    approve_goods_receipt_confirmation: "Bạn có chắc muốn duyệt phiếu nhập kho này?",
    reject_goods_receipt: "Từ chối phiếu nhập kho",
    reject_goods_receipt_confirmation: "Bạn có chắc muốn từ chối phiếu nhập kho này?",
    cancel_goods_receipt: "Hủy phiếu nhập kho",
    cancel_goods_receipt_confirmation: "Bạn có chắc muốn hủy phiếu nhập kho này?",
    goods_receipt_approved: "Duyệt phiếu nhập kho thành công",
    goods_receipt_rejected: "Từ chối phiếu nhập kho thành công",
    goods_receipt_cancelled: "Hủy phiếu nhập kho thành công",
    import_successful: "Nhập thành công",
    export_successful: "Xuất thành công",
    enter_lot_number: "Nhập số lô",
    search_model: "Tìm kiếm mô hình...",
    no_models_found: "Không tìm thấy mô hình",
    edit_details: "Sửa chi tiết",
    select_model_first: "Chọn mô hình trước",
    fill_required_fields_first: "Điền các trường bắt buộc trước (Kho, Số tham chiếu cho PO/Chuyển kho)",
    qty_exceeds_onhand: "Số lượng không được vượt quá tồn kho",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }
  return context
}
